# Generated by Django 3.2.7 on 2021-09-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('January', 'JANUARY'), ('February', 'FEBRUARY'), ('March', 'MARCH'), ('April', 'APRIL'), ('May', 'MAY'), ('June', 'JUNE'), ('July', 'JULY'), ('August', 'AUGUST'), ('September', 'SEPTEMBER'), ('October', 'OCTOBER'), ('November', 'NOVEMBER'), ('December', 'DECEMBER')], default='January', max_length=20)),
                ('dayofweek', models.CharField(choices=[('Monday', 'MONDAY'), ('Tuesday', 'TUESDAY'), ('Wednesday', 'WEDNESDAY'), ('Thursday', 'THURSDAY'), ('Friday', 'FRIDAY'), ('Saturday', 'SATURDAY'), ('Sunday', 'SUNDAY')], default='Monday', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='FavDayOfWeek',
        ),
        migrations.DeleteModel(
            name='FavMonth',
        ),
    ]
